version: '3'
services:
  myproj-backend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    networks:
      - myproj-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    networks:
      - myproj-network

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_DATABASE: myprojdb
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:

networks:
  myproj-network:
